name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Package
      if: github.ref == 'refs/heads/main'
      run: dotnet pack -c Release -o . bitofa.helper.csproj
    - name: Publish
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
    #- name: Publish bitofa.helper
    #  uses: brandedoutcast/publish-nuget@v2.5.5
    #  with:
    #      PROJECT_FILE_PATH: bitofa.helper/bitofa.helper.csproj
    #      NUGET_KEY: ${{secrets.NUGET_API_KEY}}
